apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmChartInflationGenerator:
- chartName: postgresql
  chartRepoUrl: https://charts.bitnami.com/bitnami
  chartVersion: 11.6.5
  releaseName: postgresql-analytics
  values: values.yaml
