apiVersion: v1
kind: Service
metadata:
  name: backoffice
  labels:
    app: backoffice
    role: application
spec:
  selector:
    app: backoffice
    role: application
  type: NodePort
  ports:  
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000